services:
  db-server:
    image: mariadb:11.4
    container_name: db-server
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: nutritrack
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mi-api-flask:
    build:
      context: ./backend
    container_name: mi-api-flask
    restart: unless-stopped
    depends_on:
      - db-server
    environment:
      DB_DRIVER: MariaDB ODBC 3.1 Driver
      DB_HOST: db-server
      DB_PORT: 3306
      DB_NAME: nutritrack
      DB_USER: root
      DB_PASSWORD: rootpassword
      JWT_SECRET: nutritrack_flask_secret_2026
    ports:
      - "5000:5000"

  mi-sitio-web:
    build:
      context: ./frontend
    container_name: mi-sitio-web
    restart: unless-stopped
    depends_on:
      - mi-api-flask
    ports:
      - "80:80"

volumes:
  mariadb_data:
